alias rs='`git rev-parse --show-cdup`bin/rails'
alias rp='`git rev-parse --show-cdup`bin/rails console'
alias rg='`git rev-parse --show-cdup`bin/rails generate'
alias rk='`git rev-parse --show-cdup`bin/rake'
alias mg='`git rev-parse --show-cdup`bin/rake db:migrate'
alias rap='RAILS_ENV=production be rake assets:precompile --trace'
alias spring='`git rev-parse --show-cdup`bin/spring'
